name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  core_x:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 
  freezed: 
  json_serializable: ^6.6.1
  retrofit_generator: 
  json_annotation:
flutter:
  uses-material-design: true
